name: Simple CI/CD

on:
  push:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Run Unit Tests
        run: echo "Running UNIT tests..."

      - name: Run Integration Tests
        run: echo "Running INTEGRATION tests..."

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: echo "Building DOCKER image..."

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        run: echo "Deploying to SERVER..."
